package Users;

import java.util.concurrent.atomic.AtomicInteger;

public class User {
    private String username;
    private String password;
    private int score;
    private boolean isGuest;
    private boolean isLoggedIn;
    private String token = null;

    User(String username, String password) {
        this.username = username;
        this.password = password;
        this.isLoggedIn = false;
    }
    public User() {}

    public int getScore() { return this.score;}
    public void setScore(int score) { this.score = score;}

    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }


    public String getToken() {
        return token;
    }
    public void setToken(String token) {
        this.token = token;
    }

    public boolean isGuest() {
        return isGuest;
    }
    public void setGuest(boolean guest) {isGuest = guest;}

    public boolean isLoggedIn() {
        return isLoggedIn;
    }

    public void setLoggedIn(boolean loggedIn) {
        isLoggedIn = loggedIn;
    }

    // Auto-generated by IntelliJ
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        User user = (User) o;

        return isGuest == user.isGuest && username.equals(user.username) && password.equals(user.password);

    }
}
